In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a-b)

[0 0 0]


In [3]:
PI = 3.14159265358979323
SOLAR_MASS = 4 * PI * PI
DAYS_PER_YEAR = 365.24

In [4]:
sun = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, SOLAR_MASS])
jupiter = np.array([4.84143144246472090e+00, -1.16032004402742839e+00, -1.03622044471123109e-01, 
                    1.66007664274403694e-03, 7.69901118419740425e-03, -6.90460016972063023e-05, 
                    9.54791938424326609e-04])
saturn = np.array([8.34336671824457987e+00, 4.12479856412430479e+00, -4.03523417114321381e-01, 
                   -2.76742510726862411e-03, 4.99852801234917238e-03, 2.30417297573763929e-05, 
                   2.85885980666130812e-04])
uranus = np.array([1.28943695621391310e+01, -1.51111514016986312e+01, -2.23307578892655734e-01, 
                   2.96460137564761618e-03, 2.37847173959480950e-03, -2.96589568540237556e-05, 
                   4.36624404335156298e-05]) 
neptune = np.array([1.53796971148509165e+01, -2.59193146099879641e+01, 1.79258772950371181e-01, 
                    2.68067772490389322e-03, 1.62824170038242295e-03, -9.51592254519715870e-05, 
                    5.15138902046611451e-05])       
print(sun)

[  0.          0.          0.          0.          0.          0.
  39.4784176]


In [5]:
bodies_ndarray = np.vstack((sun, jupiter, saturn, uranus, neptune))
print(bodies_ndarray)
bodies_ndarray[1:, 3:6] *= DAYS_PER_YEAR
print(bodies_ndarray)
bodies_ndarray[1:, -1:] *= SOLAR_MASS
print(bodies_ndarray)

[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   3.94784176e+01]
 [  4.84143144e+00  -1.16032004e+00  -1.03622044e-01   1.66007664e-03
    7.69901118e-03  -6.90460017e-05   9.54791938e-04]
 [  8.34336672e+00   4.12479856e+00  -4.03523417e-01  -2.76742511e-03
    4.99852801e-03   2.30417298e-05   2.85885981e-04]
 [  1.28943696e+01  -1.51111514e+01  -2.23307579e-01   2.96460138e-03
    2.37847174e-03  -2.96589569e-05   4.36624404e-05]
 [  1.53796971e+01  -2.59193146e+01   1.79258773e-01   2.68067772e-03
    1.62824170e-03  -9.51592255e-05   5.15138902e-05]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   3.94784176e+01]
 [  4.84143144e+00  -1.16032004e+00  -1.03622044e-01   6.06326393e-01
    2.81198684e+00  -2.52183617e-02   9.54791938e-04]
 [  8.34336672e+00   4.12479856e+00  -4.03523417e-01  -1.01077435e+00
    1.82566237e+00   8.41576138e-03   2.85885981e-04]
 [  1.2

In [6]:
print(bodies_ndarray[1:, 3:6] * DAYS_PER_YEAR) 
bodies_ndarray[1:, 3:6] *= DAYS_PER_YEAR
print(bodies_ndarray)

[[  221.45465178  1027.05007524    -9.21075441]
 [ -369.1752222    666.80492447     3.07377269]
 [  395.47858719   317.28874276    -3.95651248]
 [  357.60309904   217.20786227   -12.69426519]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   3.94784176e+01]
 [  4.84143144e+00  -1.16032004e+00  -1.03622044e-01   2.21454652e+02
    1.02705008e+03  -9.21075441e+00   3.76936749e-02]
 [  8.34336672e+00   4.12479856e+00  -4.03523417e-01  -3.69175222e+02
    6.66804924e+02   3.07377269e+00   1.12863261e-02]
 [  1.28943696e+01  -1.51111514e+01  -2.23307579e-01   3.95478587e+02
    3.17288743e+02  -3.95651248e+00   1.72372406e-03]
 [  1.53796971e+01  -2.59193146e+01   1.79258773e-01   3.57603099e+02
    2.17207862e+02  -1.26942652e+01   2.03368687e-03]]


In [7]:
print(bodies_ndarray[:, 3:6])
print(bodies_ndarray[:, -1].T)
print((bodies_ndarray[:, 3:6].T * bodies_ndarray[:, -1]).T)

[[    0.             0.             0.        ]
 [  221.45465178  1027.05007524    -9.21075441]
 [ -369.1752222    666.80492447     3.07377269]
 [  395.47858719   317.28874276    -3.95651248]
 [  357.60309904   217.20786227   -12.69426519]]
[  3.94784176e+01   3.76936749e-02   1.12863261e-02   1.72372406e-03
   2.03368687e-03]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.34743964e+00   3.87132916e+01  -3.47187182e-01]
 [ -4.16663196e+00   7.52577784e+00   3.46916010e-02]
 [  6.81695955e-01   5.46918239e-01  -6.81993575e-03]
 [  7.27252727e-01   4.41732778e-01  -2.58161604e-02]]


In [8]:
bodies_ndarray[0:1, 0:3] = ((bodies_ndarray[:, 3:6].T * bodies_ndarray[:, -1]).T).sum(axis=0)
print(bodies_ndarray[0:1, 0:3])


[[  5.58975637  47.22772047  -0.34513168]]


In [9]:
bodies_ndarray[0:1, 0:3] /= bodies_ndarray[0:1, -1:]
print(bodies_ndarray[0:1, 0:3])

[[ 0.14159018  1.19629213 -0.00874229]]


In [10]:
import itertools
all_combinations = list(itertools.combinations(range(0, 5), 2))

In [11]:
np.dot(np.array([1,2,3]), np.array([1,2,3]))

14

In [12]:
for body_idx_1, body_idx_2 in all_combinations:
    deltas = bodies_ndarray[body_idx_1, 0:3] - bodies_ndarray[body_idx_2, 0:3]
    mag = 0.01 * (np.linalg.norm(deltas) ** (0.5))
    bodies_ndarray[body_idx_1, 0:3] -= deltas * mag * bodies_ndarray[body_idx_1, -1:]
    bodies_ndarray[body_idx_2, 0:3] += deltas * mag * bodies_ndarray[body_idx_2, -1:]
    bodies_ndarray[:, 0:3] += 0.01 * bodies_ndarray[:, 3:6]
    print(bodies_ndarray[:, 3:6])
    

[[    0.             0.             0.        ]
 [  221.45465178  1027.05007524    -9.21075441]
 [ -369.1752222    666.80492447     3.07377269]
 [  395.47858719   317.28874276    -3.95651248]
 [  357.60309904   217.20786227   -12.69426519]]
[[    0.             0.             0.        ]
 [  221.45465178  1027.05007524    -9.21075441]
 [ -369.1752222    666.80492447     3.07377269]
 [  395.47858719   317.28874276    -3.95651248]
 [  357.60309904   217.20786227   -12.69426519]]
[[    0.             0.             0.        ]
 [  221.45465178  1027.05007524    -9.21075441]
 [ -369.1752222    666.80492447     3.07377269]
 [  395.47858719   317.28874276    -3.95651248]
 [  357.60309904   217.20786227   -12.69426519]]
[[    0.             0.             0.        ]
 [  221.45465178  1027.05007524    -9.21075441]
 [ -369.1752222    666.80492447     3.07377269]
 [  395.47858719   317.28874276    -3.95651248]
 [  357.60309904   217.20786227   -12.69426519]]
[[    0.             0.             

In [13]:
e = 0.
for body_idx_1, body_idx_2 in all_combinations:
        # compute deltas
        deltas = bodies_ndarray[body_idx_1, 0:3] - bodies_ndarray[body_idx_2, 0:3]
        # compute energy
        e -= bodies_ndarray[body_idx_1, -1] * bodies_ndarray[body_idx_2, -1] * np.linalg.norm(deltas)

for i in range(bodies_ndarray.shape[0]):
    e += bodies_ndarray[i, -1] * (np.linalg.norm(bodies_ndarray[i, 3:6]) ** 2) / 2
    
print(e)

24276.1226094


In [14]:
c.shape

NameError: name 'c' is not defined

In [15]:
((bodies_ndarray[:, 3:6].T * bodies_ndarray[:, -1]).T).sum(axis=0)

array([  5.58975637,  47.22772047,  -0.34513168])

In [16]:
np.linalg.norm(np.hstack((a,b)))

5.2915026221291814

In [24]:
%timeit np.linalg.norm(bodies_ndarray[1, 3:6]) ** 2
print(np.linalg.norm(bodies_ndarray[1, 3:6]) ** 2)

The slowest run took 6.21 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 26.7 µs per loop
1103958.85784


In [23]:
%timeit np.sum(bodies_ndarray[1, 3:6] ** 2)

The slowest run took 300.38 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 17.8 µs per loop


In [22]:
np.array([1,2,3]) ** 2

array([1, 4, 9])

In [32]:
def fun_1(e=0.):
    for i in range(bodies_ndarray.shape[0]): 
        e += bodies_ndarray[i, -1] * np.sum(bodies_ndarray[i, 3:6] ** 2) / 2.0
        
def fun_2():
    return np.sum( (bodies_ndarray[i, -1] * np.sum(bodies_ndarray[i, 3:6] ** 2) / 2.0) for i in range(bodies_ndarray.shape[0]))

%timeit fun_1()
%timeit fun_2()

1000 loops, best of 3: 145 µs per loop
10000 loops, best of 3: 117 µs per loop


In [42]:
%timeit bodies_ndarray[:, 0:3] += dt * bodies_ndarray[:, 3:6]


NameError: name 'dt' is not defined

In [44]:
%timeit bodies_ndarray[:, 0:3] += 0.01 * bodies_ndarray[:, 3:6]

The slowest run took 5.31 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 19.6 µs per loop


In [50]:
np.dot(np.vstack((a,b)), np.vstack((a,b)))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [51]:
np.vstack((a,b)) * np.vstack((a,b))

array([[1, 4, 9],
       [1, 4, 9]])

In [52]:
np.vstack((a,b))

array([[1, 2, 3],
       [1, 2, 3]])

In [53]:
np.sqrt((a,b))

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 1.        ,  1.41421356,  1.73205081]])

In [54]:
range(26)

range(0, 26)

In [55]:
range(1,26)

range(1, 26)

In [56]:
list(range(1,26))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [59]:
class C:
  dangerous = 2

c1 = C()
c2 = C()
print(c1.dangerous)
c1.dangerous = 3
print(c1.dangerous)
print(c2.dangerous) 
del c1.dangerous
print(c1.dangerous) 
C.dangerous = 3
print(c2.dangerous)

2
3
2
2
3
